version: '3.8'
services:
    db:
        image: postgres:14.3-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=db_order
        ports:
            - '5432:5432'
        networks:
            - myNet
        volumes:
            - db:/var/lib/postgresql_order/data
    redis_order:
        image: sickp/alpine-redis:3.2.2
        ports:
            - "6380:6379"
        networks:
            - myNet

    order_api:
        image: order-api:latest
        ports:
            - "8080:8080"
        networks:
            - myNet

networks:
    myNet:
        driver: bridge
volumes:
    db:
        driver: local